//go:build linux && arm64

package sec

import (
	"fmt"

	"golang.org/x/sys/unix"
)

type SCTable struct {
	nameToInt map[string]int
	intToName map[int]string
}

var SCTbl *SCTable

func (t *SCTable) Init() {
	t.nameToInt = make(map[string]int)
	t.intToName = make(map[int]string)
	for name, id := range map[string]int{
		"io_setup":                unix.SYS_IO_SETUP,
		"io_destroy":              unix.SYS_IO_DESTROY,
		"io_submit":               unix.SYS_IO_SUBMIT,
		"io_cancel":               unix.SYS_IO_CANCEL,
		"io_getevents":            unix.SYS_IO_GETEVENTS,
		"setxattr":                unix.SYS_SETXATTR,
		"lsetxattr":               unix.SYS_LSETXATTR,
		"fsetxattr":               unix.SYS_FSETXATTR,
		"getxattr":                unix.SYS_GETXATTR,
		"lgetxattr":               unix.SYS_LGETXATTR,
		"fgetxattr":               unix.SYS_FGETXATTR,
		"listxattr":               unix.SYS_LISTXATTR,
		"llistxattr":              unix.SYS_LLISTXATTR,
		"flistxattr":              unix.SYS_FLISTXATTR,
		"removexattr":             unix.SYS_REMOVEXATTR,
		"lremovexattr":            unix.SYS_LREMOVEXATTR,
		"fremovexattr":            unix.SYS_FREMOVEXATTR,
		"getcwd":                  unix.SYS_GETCWD,
		"lookup_dcookie":          unix.SYS_LOOKUP_DCOOKIE,
		"eventfd2":                unix.SYS_EVENTFD2,
		"epoll_create1":           unix.SYS_EPOLL_CREATE1,
		"epoll_ctl":               unix.SYS_EPOLL_CTL,
		"epoll_pwait":             unix.SYS_EPOLL_PWAIT,
		"dup":                     unix.SYS_DUP,
		"dup3":                    unix.SYS_DUP3,
		"fcntl":                   unix.SYS_FCNTL,
		"inotify_init1":           unix.SYS_INOTIFY_INIT1,
		"inotify_add_watch":       unix.SYS_INOTIFY_ADD_WATCH,
		"inotify_rm_watch":        unix.SYS_INOTIFY_RM_WATCH,
		"ioctl":                   unix.SYS_IOCTL,
		"ioprio_set":              unix.SYS_IOPRIO_SET,
		"ioprio_get":              unix.SYS_IOPRIO_GET,
		"flock":                   unix.SYS_FLOCK,
		"mknodat":                 unix.SYS_MKNODAT,
		"mkdirat":                 unix.SYS_MKDIRAT,
		"unlinkat":                unix.SYS_UNLINKAT,
		"symlinkat":               unix.SYS_SYMLINKAT,
		"linkat":                  unix.SYS_LINKAT,
		"renameat":                unix.SYS_RENAMEAT,
		"umount2":                 unix.SYS_UMOUNT2,
		"mount":                   unix.SYS_MOUNT,
		"pivot_root":              unix.SYS_PIVOT_ROOT,
		"nfsservctl":              unix.SYS_NFSSERVCTL,
		"statfs":                  unix.SYS_STATFS,
		"fstatfs":                 unix.SYS_FSTATFS,
		"truncate":                unix.SYS_TRUNCATE,
		"ftruncate":               unix.SYS_FTRUNCATE,
		"fallocate":               unix.SYS_FALLOCATE,
		"faccessat":               unix.SYS_FACCESSAT,
		"chdir":                   unix.SYS_CHDIR,
		"fchdir":                  unix.SYS_FCHDIR,
		"chroot":                  unix.SYS_CHROOT,
		"fchmod":                  unix.SYS_FCHMOD,
		"fchmodat":                unix.SYS_FCHMODAT,
		"fchownat":                unix.SYS_FCHOWNAT,
		"fchown":                  unix.SYS_FCHOWN,
		"openat":                  unix.SYS_OPENAT,
		"close":                   unix.SYS_CLOSE,
		"vhangup":                 unix.SYS_VHANGUP,
		"pipe2":                   unix.SYS_PIPE2,
		"quotactl":                unix.SYS_QUOTACTL,
		"getdents64":              unix.SYS_GETDENTS64,
		"lseek":                   unix.SYS_LSEEK,
		"read":                    unix.SYS_READ,
		"write":                   unix.SYS_WRITE,
		"readv":                   unix.SYS_READV,
		"writev":                  unix.SYS_WRITEV,
		"pread64":                 unix.SYS_PREAD64,
		"pwrite64":                unix.SYS_PWRITE64,
		"preadv":                  unix.SYS_PREADV,
		"pwritev":                 unix.SYS_PWRITEV,
		"sendfile":                unix.SYS_SENDFILE,
		"pselect6":                unix.SYS_PSELECT6,
		"ppoll":                   unix.SYS_PPOLL,
		"signalfd4":               unix.SYS_SIGNALFD4,
		"vmsplice":                unix.SYS_VMSPLICE,
		"splice":                  unix.SYS_SPLICE,
		"tee":                     unix.SYS_TEE,
		"readlinkat":              unix.SYS_READLINKAT,
		"newfstatat":              unix.SYS_NEWFSTATAT,
		"fstat":                   unix.SYS_FSTAT,
		"sync":                    unix.SYS_SYNC,
		"fsync":                   unix.SYS_FSYNC,
		"fdatasync":               unix.SYS_FDATASYNC,
		"sync_file_range":         unix.SYS_SYNC_FILE_RANGE,
		"timerfd_create":          unix.SYS_TIMERFD_CREATE,
		"timerfd_settime":         unix.SYS_TIMERFD_SETTIME,
		"timerfd_gettime":         unix.SYS_TIMERFD_GETTIME,
		"utimensat":               unix.SYS_UTIMENSAT,
		"acct":                    unix.SYS_ACCT,
		"capget":                  unix.SYS_CAPGET,
		"capset":                  unix.SYS_CAPSET,
		"personality":             unix.SYS_PERSONALITY,
		"exit":                    unix.SYS_EXIT,
		"exit_group":              unix.SYS_EXIT_GROUP,
		"waitid":                  unix.SYS_WAITID,
		"set_tid_address":         unix.SYS_SET_TID_ADDRESS,
		"unshare":                 unix.SYS_UNSHARE,
		"futex":                   unix.SYS_FUTEX,
		"set_robust_list":         unix.SYS_SET_ROBUST_LIST,
		"get_robust_list":         unix.SYS_GET_ROBUST_LIST,
		"nanosleep":               unix.SYS_NANOSLEEP,
		"getitimer":               unix.SYS_GETITIMER,
		"setitimer":               unix.SYS_SETITIMER,
		"kexec_load":              unix.SYS_KEXEC_LOAD,
		"init_module":             unix.SYS_INIT_MODULE,
		"delete_module":           unix.SYS_DELETE_MODULE,
		"timer_create":            unix.SYS_TIMER_CREATE,
		"timer_gettime":           unix.SYS_TIMER_GETTIME,
		"timer_getoverrun":        unix.SYS_TIMER_GETOVERRUN,
		"timer_settime":           unix.SYS_TIMER_SETTIME,
		"timer_delete":            unix.SYS_TIMER_DELETE,
		"clock_settime":           unix.SYS_CLOCK_SETTIME,
		"clock_gettime":           unix.SYS_CLOCK_GETTIME,
		"clock_getres":            unix.SYS_CLOCK_GETRES,
		"clock_nanosleep":         unix.SYS_CLOCK_NANOSLEEP,
		"syslog":                  unix.SYS_SYSLOG,
		"ptrace":                  unix.SYS_PTRACE,
		"sched_setparam":          unix.SYS_SCHED_SETPARAM,
		"sched_setscheduler":      unix.SYS_SCHED_SETSCHEDULER,
		"sched_getscheduler":      unix.SYS_SCHED_GETSCHEDULER,
		"sched_getparam":          unix.SYS_SCHED_GETPARAM,
		"sched_setaffinity":       unix.SYS_SCHED_SETAFFINITY,
		"sched_getaffinity":       unix.SYS_SCHED_GETAFFINITY,
		"sched_yield":             unix.SYS_SCHED_YIELD,
		"sched_get_priority_max":  unix.SYS_SCHED_GET_PRIORITY_MAX,
		"sched_get_priority_min":  unix.SYS_SCHED_GET_PRIORITY_MIN,
		"sched_rr_get_interval":   unix.SYS_SCHED_RR_GET_INTERVAL,
		"restart_syscall":         unix.SYS_RESTART_SYSCALL,
		"kill":                    unix.SYS_KILL,
		"tkill":                   unix.SYS_TKILL,
		"tgkill":                  unix.SYS_TGKILL,
		"sigaltstack":             unix.SYS_SIGALTSTACK,
		"rt_sigsuspend":           unix.SYS_RT_SIGSUSPEND,
		"rt_sigaction":            unix.SYS_RT_SIGACTION,
		"rt_sigprocmask":          unix.SYS_RT_SIGPROCMASK,
		"rt_sigpending":           unix.SYS_RT_SIGPENDING,
		"rt_sigtimedwait":         unix.SYS_RT_SIGTIMEDWAIT,
		"rt_sigqueueinfo":         unix.SYS_RT_SIGQUEUEINFO,
		"rt_sigreturn":            unix.SYS_RT_SIGRETURN,
		"setpriority":             unix.SYS_SETPRIORITY,
		"getpriority":             unix.SYS_GETPRIORITY,
		"reboot":                  unix.SYS_REBOOT,
		"setregid":                unix.SYS_SETREGID,
		"setgid":                  unix.SYS_SETGID,
		"setreuid":                unix.SYS_SETREUID,
		"setuid":                  unix.SYS_SETUID,
		"setresuid":               unix.SYS_SETRESUID,
		"getresuid":               unix.SYS_GETRESUID,
		"setresgid":               unix.SYS_SETRESGID,
		"getresgid":               unix.SYS_GETRESGID,
		"setfsuid":                unix.SYS_SETFSUID,
		"setfsgid":                unix.SYS_SETFSGID,
		"times":                   unix.SYS_TIMES,
		"setpgid":                 unix.SYS_SETPGID,
		"getpgid":                 unix.SYS_GETPGID,
		"getsid":                  unix.SYS_GETSID,
		"setsid":                  unix.SYS_SETSID,
		"getgroups":               unix.SYS_GETGROUPS,
		"setgroups":               unix.SYS_SETGROUPS,
		"uname":                   unix.SYS_UNAME,
		"sethostname":             unix.SYS_SETHOSTNAME,
		"setdomainname":           unix.SYS_SETDOMAINNAME,
		"getrlimit":               unix.SYS_GETRLIMIT,
		"setrlimit":               unix.SYS_SETRLIMIT,
		"getrusage":               unix.SYS_GETRUSAGE,
		"umask":                   unix.SYS_UMASK,
		"prctl":                   unix.SYS_PRCTL,
		"getcpu":                  unix.SYS_GETCPU,
		"gettimeofday":            unix.SYS_GETTIMEOFDAY,
		"settimeofday":            unix.SYS_SETTIMEOFDAY,
		"adjtimex":                unix.SYS_ADJTIMEX,
		"getpid":                  unix.SYS_GETPID,
		"getppid":                 unix.SYS_GETPPID,
		"getuid":                  unix.SYS_GETUID,
		"geteuid":                 unix.SYS_GETEUID,
		"getgid":                  unix.SYS_GETGID,
		"getegid":                 unix.SYS_GETEGID,
		"gettid":                  unix.SYS_GETTID,
		"sysinfo":                 unix.SYS_SYSINFO,
		"mq_open":                 unix.SYS_MQ_OPEN,
		"mq_unlink":               unix.SYS_MQ_UNLINK,
		"mq_timedsend":            unix.SYS_MQ_TIMEDSEND,
		"mq_timedreceive":         unix.SYS_MQ_TIMEDRECEIVE,
		"mq_notify":               unix.SYS_MQ_NOTIFY,
		"mq_getsetattr":           unix.SYS_MQ_GETSETATTR,
		"msgget":                  unix.SYS_MSGGET,
		"msgctl":                  unix.SYS_MSGCTL,
		"msgrcv":                  unix.SYS_MSGRCV,
		"msgsnd":                  unix.SYS_MSGSND,
		"semget":                  unix.SYS_SEMGET,
		"semctl":                  unix.SYS_SEMCTL,
		"semtimedop":              unix.SYS_SEMTIMEDOP,
		"semop":                   unix.SYS_SEMOP,
		"shmget":                  unix.SYS_SHMGET,
		"shmctl":                  unix.SYS_SHMCTL,
		"shmat":                   unix.SYS_SHMAT,
		"shmdt":                   unix.SYS_SHMDT,
		"socket":                  unix.SYS_SOCKET,
		"socketpair":              unix.SYS_SOCKETPAIR,
		"bind":                    unix.SYS_BIND,
		"listen":                  unix.SYS_LISTEN,
		"accept":                  unix.SYS_ACCEPT,
		"connect":                 unix.SYS_CONNECT,
		"getsockname":             unix.SYS_GETSOCKNAME,
		"getpeername":             unix.SYS_GETPEERNAME,
		"sendto":                  unix.SYS_SENDTO,
		"recvfrom":                unix.SYS_RECVFROM,
		"setsockopt":              unix.SYS_SETSOCKOPT,
		"getsockopt":              unix.SYS_GETSOCKOPT,
		"shutdown":                unix.SYS_SHUTDOWN,
		"sendmsg":                 unix.SYS_SENDMSG,
		"recvmsg":                 unix.SYS_RECVMSG,
		"readahead":               unix.SYS_READAHEAD,
		"brk":                     unix.SYS_BRK,
		"munmap":                  unix.SYS_MUNMAP,
		"mremap":                  unix.SYS_MREMAP,
		"add_key":                 unix.SYS_ADD_KEY,
		"request_key":             unix.SYS_REQUEST_KEY,
		"keyctl":                  unix.SYS_KEYCTL,
		"clone":                   unix.SYS_CLONE,
		"execve":                  unix.SYS_EXECVE,
		"mmap":                    unix.SYS_MMAP,
		"fadvise64":               unix.SYS_FADVISE64,
		"swapon":                  unix.SYS_SWAPON,
		"swapoff":                 unix.SYS_SWAPOFF,
		"mprotect":                unix.SYS_MPROTECT,
		"msync":                   unix.SYS_MSYNC,
		"mlock":                   unix.SYS_MLOCK,
		"munlock":                 unix.SYS_MUNLOCK,
		"mlockall":                unix.SYS_MLOCKALL,
		"munlockall":              unix.SYS_MUNLOCKALL,
		"mincore":                 unix.SYS_MINCORE,
		"madvise":                 unix.SYS_MADVISE,
		"remap_file_pages":        unix.SYS_REMAP_FILE_PAGES,
		"mbind":                   unix.SYS_MBIND,
		"get_mempolicy":           unix.SYS_GET_MEMPOLICY,
		"set_mempolicy":           unix.SYS_SET_MEMPOLICY,
		"migrate_pages":           unix.SYS_MIGRATE_PAGES,
		"move_pages":              unix.SYS_MOVE_PAGES,
		"rt_tgsigqueueinfo":       unix.SYS_RT_TGSIGQUEUEINFO,
		"perf_event_open":         unix.SYS_PERF_EVENT_OPEN,
		"accept4":                 unix.SYS_ACCEPT4,
		"recvmmsg":                unix.SYS_RECVMMSG,
		"arch_specific_syscall":   unix.SYS_ARCH_SPECIFIC_SYSCALL,
		"wait4":                   unix.SYS_WAIT4,
		"prlimit64":               unix.SYS_PRLIMIT64,
		"fanotify_init":           unix.SYS_FANOTIFY_INIT,
		"fanotify_mark":           unix.SYS_FANOTIFY_MARK,
		"name_to_handle_at":       unix.SYS_NAME_TO_HANDLE_AT,
		"open_by_handle_at":       unix.SYS_OPEN_BY_HANDLE_AT,
		"clock_adjtime":           unix.SYS_CLOCK_ADJTIME,
		"syncfs":                  unix.SYS_SYNCFS,
		"setns":                   unix.SYS_SETNS,
		"sendmmsg":                unix.SYS_SENDMMSG,
		"process_vm_readv":        unix.SYS_PROCESS_VM_READV,
		"process_vm_writev":       unix.SYS_PROCESS_VM_WRITEV,
		"kcmp":                    unix.SYS_KCMP,
		"finit_module":            unix.SYS_FINIT_MODULE,
		"sched_setattr":           unix.SYS_SCHED_SETATTR,
		"sched_getattr":           unix.SYS_SCHED_GETATTR,
		"renameat2":               unix.SYS_RENAMEAT2,
		"seccomp":                 unix.SYS_SECCOMP,
		"getrandom":               unix.SYS_GETRANDOM,
		"memfd_create":            unix.SYS_MEMFD_CREATE,
		"bpf":                     unix.SYS_BPF,
		"execveat":                unix.SYS_EXECVEAT,
		"userfaultfd":             unix.SYS_USERFAULTFD,
		"membarrier":              unix.SYS_MEMBARRIER,
		"mlock2":                  unix.SYS_MLOCK2,
		"copy_file_range":         unix.SYS_COPY_FILE_RANGE,
		"preadv2":                 unix.SYS_PREADV2,
		"pwritev2":                unix.SYS_PWRITEV2,
		"pkey_mprotect":           unix.SYS_PKEY_MPROTECT,
		"pkey_alloc":              unix.SYS_PKEY_ALLOC,
		"pkey_free":               unix.SYS_PKEY_FREE,
		"statx":                   unix.SYS_STATX,
		"io_pgetevents":           unix.SYS_IO_PGETEVENTS,
		"rseq":                    unix.SYS_RSEQ,
		"kexec_file_load":         unix.SYS_KEXEC_FILE_LOAD,
		"pidfd_send_signal":       unix.SYS_PIDFD_SEND_SIGNAL,
		"io_uring_setup":          unix.SYS_IO_URING_SETUP,
		"io_uring_enter":          unix.SYS_IO_URING_ENTER,
		"io_uring_register":       unix.SYS_IO_URING_REGISTER,
		"open_tree":               unix.SYS_OPEN_TREE,
		"move_mount":              unix.SYS_MOVE_MOUNT,
		"fsopen":                  unix.SYS_FSOPEN,
		"fsconfig":                unix.SYS_FSCONFIG,
		"fsmount":                 unix.SYS_FSMOUNT,
		"fspick":                  unix.SYS_FSPICK,
		"pidfd_open":              unix.SYS_PIDFD_OPEN,
		"clone3":                  unix.SYS_CLONE3,
		"close_range":             unix.SYS_CLOSE_RANGE,
		"openat2":                 unix.SYS_OPENAT2,
		"pidfd_getfd":             unix.SYS_PIDFD_GETFD,
		"faccessat2":              unix.SYS_FACCESSAT2,
		"process_madvise":         unix.SYS_PROCESS_MADVISE,
		"epoll_pwait2":            unix.SYS_EPOLL_PWAIT2,
		"mount_setattr":           unix.SYS_MOUNT_SETATTR,
		"quotactl_fd":             unix.SYS_QUOTACTL_FD,
		"landlock_create_ruleset": unix.SYS_LANDLOCK_CREATE_RULESET,
		"landlock_add_rule":       unix.SYS_LANDLOCK_ADD_RULE,
		"landlock_restrict_self":  unix.SYS_LANDLOCK_RESTRICT_SELF,
		"memfd_secret":            unix.SYS_MEMFD_SECRET,
		"process_mrelease":        unix.SYS_PROCESS_MRELEASE,
		"futex_waitv":             unix.SYS_FUTEX_WAITV,
		"set_mempolicy_home_node": unix.SYS_SET_MEMPOLICY_HOME_NODE,
		"cachestat":               unix.SYS_CACHESTAT,
		"fchmodat2":               unix.SYS_FCHMODAT2,
		"map_shadow_stack":        unix.SYS_MAP_SHADOW_STACK,
		"futex_wake":              unix.SYS_FUTEX_WAKE,
		"futex_wait":              unix.SYS_FUTEX_WAIT,
		"futex_requeue":           unix.SYS_FUTEX_REQUEUE,
		"statmount":               unix.SYS_STATMOUNT,
		"listmount":               unix.SYS_LISTMOUNT,
		"lsm_get_self_attr":       unix.SYS_LSM_GET_SELF_ATTR,
		"lsm_set_self_attr":       unix.SYS_LSM_SET_SELF_ATTR,
		"lsm_list_modules":        unix.SYS_LSM_LIST_MODULES,
		"mseal":                   unix.SYS_MSEAL,
		"setxattrat":              unix.SYS_SETXATTRAT,
		"getxattrat":              unix.SYS_GETXATTRAT,
		"listxattrat":             unix.SYS_LISTXATTRAT,
		"removexattrat":           unix.SYS_REMOVEXATTRAT,
		"open_tree_attr":          unix.SYS_OPEN_TREE_ATTR,
		"file_getattr":            468,
		"file_setattr":            469,
		"listns":                  470,
		"rseq_slice_yield":        471,
	} {
		t.nameToInt[name] = id
		t.intToName[id] = name
	}
}

func (t *SCTable) GetName(callID int) (string, error) {
	if callName, ok := t.intToName[callID]; ok {
		return callName, nil
	}
	return "", fmt.Errorf("NoCallWithID %d", callID)
}

func (t *SCTable) GetID(callName string) (int, error) {
	callID, ok := t.nameToInt[callName]
	if ok {
		return callID, nil
	}
	return -1, fmt.Errorf("NoCallNamed %s", callName)
}

func init() {
	SCTbl = new(SCTable)
	SCTbl.Init()
}
