default:
	go build .

test-c:
	@cd ./tests/c/;../../compiler

test-cpp:
	@cd ./tests/cpp;../../compiler

test-fpc:
	@cd ./tests/fpc;../../compiler

test-16g:
	@cd ./tests/16g;../../compiler

test-bigexe:
	@cd ./tests/bigexe;../../compiler

test-bomb:
	@cd ./tests/16g;../../compiler